#!/usr/bin/env node

const fcmd = require('../src');

fcmd
  .version('0.0.1')
  .description('test fcmd')
  .action(async () => {
    console.log('1');
  });

fcmd
  .command('dev', 'run a dev-server')
  .option('-p --port <port>', 'server port')
  .action((argv, options) => console.log('run dev', options.port));

fcmd.parse(process.argv)